language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9
install:
  - "pip install --use-mirrors Django==$DJANGO_VERSION"
  - "pip install --use-mirrors --editable ."
script: "django-admin.py test --settings=flows.tests.settings flows"
